version: 2
updates:
  - package-ecosystem: "npm" # Change to match your package manager (e.g., pip, maven, gradle, etc.)
    directory: "/" # Root directory of your project
    schedule:
      interval: "daily" # Can be daily, weekly, or monthly
    open-pull-requests-limit: 5
    reviewers:
      - "vikasch123"
